### PR TITLE
Removed package cl_urdf

### PR DESCRIPTION
**Pull request by jannikb**
Moved cl_urdf to roslisp_common (Issue #20 ) therefore it doens't depend on cram_physics_utils anymore so meshes now have to be loaded directly using physics-utils. bullet_reasoning is the only package that I found that is affected by this change and I changed the affected code.

### CODE REVIEW

**Comment by airballking** [comment]
@gaya- thanks for testing this, would have taken me quite some time...
@jannikb thanks for providing this

**Comment by gaya-** [comment]
@jannikb There was a little flaw in the PR: the function [```load-3d-model```](https://github.com/cram-code/cram_physics/pull/22/files#diff-3ce535b04554800915b6b1c75ba8c975R62) is not a generic function. Could you please either change that helper back into a normal function with a different name or define the ```load-3d-model``` from the utils as a generic function? Sorry I let this slip.

**Comment by jannikb** [comment]
I made the function a normal function, renamed it and opened a new pr for it.

**Comment by gaya-** [comment]
Awesome, thanks.

**Pull request merged**
